### PR TITLE
Template to use coffeescript and embark

### PR DESCRIPTION
**Pull request by millnitzluan**
Hey, this PR is to close the issue:
github: #1 
gitcoin: https://gitcoin.co/issue/embark-framework/embark-coffeescript-template/1/1311

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Looks good. I'll test in a few

**Comment by millnitzluan** [comment]
Okay, thanks

**Comment by jrainville** [comment]
Just tested. The template works well. Only two smalls changes needed:
- Comment out SimpleStorage in config/contracts.js as it tries to deploy it even if it doesn't exist
- There are 2 index files and main.js seems useless. Those files are at the root of the template

**Comment by millnitzluan** [comment]
@jrainville Done, my fault! I've forget to re-check the files

**Review by jrainville — APPROVED** [review]
Works perfectly, good work!

**Comment by iurimatias** [comment]
can confirm it's working

**Pull request merged**
